# Generated by Django 3.2.9 on 2021-12-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.IntegerField()),
                ('termfuel', models.IntegerField()),
                ('clad', models.IntegerField()),
                ('tube', models.IntegerField()),
            ],
        ),
    ]
